spring:
  spring:
    datasource:
      url: jdbc:postgresql://${SPRING_DATASOURCE_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

jwt:
  secret: ${JWT_SECRET:printforge-fallback-secret-key-123456789}
  expiration: ${JWT_EXPIRATION:86400000}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

server:
  port: ${PORT:8080}